[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "artof"
authors = [{name = "Axel Willekens", email = "axel.willekens@ilvo.vlaanderen.be"}]
dynamic = ["version", "description"]
